"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ApiError, getNotifications, markAllNotificationsRead, markNotificationRead } from "@/lib/api";
import type { Notification, NotificationPage } from "@/types";
import { useLocale } from "@/context/LocaleContext";
import { notificationCopy } from "@/lib/i18n";

export default function NotificationsPage() {
  const { locale, t } = useLocale();
  const [page, setPage] = useState<NotificationPage>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { setPage(await getNotifications()); setError(undefined); } catch (e) { setError(e instanceof Error ? e.message : t("notificationsLoadError")); } finally { setLoading(false); } };
  const loadMore = async () => { if (page?.nextOffset === undefined) return; setBusy(true); try { const next = await getNotifications(page.nextOffset); setPage({...next, items: [...page.items, ...next.items]}); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : t("notificationsLoadError")); } finally { setBusy(false); } };
  useEffect(() => { void load(); const refresh = () => void load(); window.addEventListener("idr:notification", refresh); return () => window.removeEventListener("idr:notification", refresh); }, []);
  const mark = async (item: Notification) => { if (item.readAt) return; setBusy(true); try { await markNotificationRead(item.id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("notificationsLoadError")); } finally { setBusy(false); } };
  const markAll = async () => { setBusy(true); try { await markAllNotificationsRead(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("notificationsLoadError")); } finally { setBusy(false); } };
  return <section className="mx-auto max-w-4xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{t("notifications")}</h1><p className="text-sm text-slate-500">{page?.unreadCount ?? 0} {t("unread")}</p></div><button disabled={busy || !page?.unreadCount} onClick={() => void markAll()} className="min-h-11 rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-50">{t("markAllRead")}</button></div>{loading ? <p>{t("loading")}</p> : error ? <div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error} <button onClick={() => void load()} className="underline">{t("retry")}</button></div> : !page?.items.length ? <p className="rounded-xl border p-5 text-slate-500">{t("noNotifications")}</p> : <><ul className="space-y-3">{page.items.map((item) => { const copy = notificationCopy(item.eventType,item.title,item.message,locale); return <li key={item.id} className={`rounded-xl border p-4 ${item.readAt ? "bg-white" : "border-blue-200 bg-blue-50"}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{copy[0]}</p><p className="text-sm text-slate-600">{copy[1]}</p><time className="text-xs text-slate-500">{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.createdAt))}</time>{item.entityType === "task" && item.entityId && <Link className="ml-3 text-sm text-blue-700 underline" href="/tasks">{t("viewTask")}</Link>}</div>{!item.readAt && <button disabled={busy} onClick={() => void mark(item)} className="min-h-10 rounded border px-3 text-sm">{t("markRead")}</button>}</div></li>})}</ul>{page.nextOffset !== undefined && <button disabled={busy} onClick={()=>void loadMore()} className="mt-4 min-h-11 rounded border px-4">{t("loadMore")}</button>}</>}</section>;
}
